//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItemFormAjax.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xxItemCodeFormulas
    {
        public int FormulaID { get; set; }
        public string FormulaDescription { get; set; }
        public string PercentOfIngreds { get; set; }
        public string INOUT { get; set; }
        public string Ingredient { get; set; }
        public Nullable<double> QTY { get; set; }
        public string UOM { get; set; }
        public string NewIngredient { get; set; }
        public string FCMadeLike { get; set; }
        public string FCAvgPressFillHrs { get; set; }
        public string FCTotalHoursMilled { get; set; }
        public string FCExpectedYield { get; set; }
        public string MMadeLike { get; set; }
        public string MTimeToLoad { get; set; }
        public string MTimeToMix { get; set; }
        public string MTimeToDump { get; set; }
        public string MTimeToTest { get; set; }
        public string TMadeLike { get; set; }
        public string TClassifiedHrs { get; set; }
        public string TPressFillHrs { get; set; }
        public string TT1Yield { get; set; }
        public string TF1Yield { get; set; }
        public string Specifications { get; set; }
        public string GrindingMedia { get; set; }
        public string LNumber { get; set; }
    }
}
