//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItemFormAjax.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xxItemCodeTests
    {
        public int TestID { get; set; }
        public string QCTestID { get; set; }
        public string Required { get; set; }
        public string TestFrequency { get; set; }
        public string MinValue { get; set; }
        public string MaxValue { get; set; }
        public string TargetValue { get; set; }
        public string UOM { get; set; }
        public string QualitativeValue { get; set; }
        public string Comments { get; set; }
    }
}
