//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItemFormAjax.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xxItemForm
    {
        public int ItemID { get; set; }
        public int HeaderID { get; set; }
        public string Formula { get; set; }
        public string Lnumber { get; set; }
        public string PostTreated { get; set; }
        public string Purity { get; set; }
        public string Metal { get; set; }
        public string StaticLiner { get; set; }
        public string UOM { get; set; }
        public string QTYPERPKG { get; set; }
    }
}
