//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItemFormAjax.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xxItemHeader
    {
        public int ItemID { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ProductDesription { get; set; }
        public string NewOrExisting { get; set; }
        public string ShelfLife { get; set; }
        public string ProductStatus { get; set; }
        public string Lnumber { get; set; }
        public string Company { get; set; }
        public string Waterborne { get; set; }
        public string Characteristics { get; set; }
        public string Geometry { get; set; }
        public string Micron { get; set; }
        public string PhysicalForm { get; set; }
        public string Solvent { get; set; }
        public string SurfaceTreatment { get; set; }
        public string System { get; set; }
        public string TypeApplication { get; set; }
        public string SMCTruckPricePerLB { get; set; }
        public string Packages { get; set; }
        public string StaticDissipativeLiner { get; set; }
        public string WhereWillProductBeUsed { get; set; }
        public string ProductClass { get; set; }
        public string Market { get; set; }
        public string MarketSegment { get; set; }
        public string TradeNameFirst { get; set; }
        public string TradeNameSecond { get; set; }
        public string ProductClassLeaf { get; set; }
        public string ProductClassCharacteristic { get; set; }
        public string Carrier { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> RequestedDate { get; set; }
        public string CopyDownToCompanies { get; set; }
        public string Purchased { get; set; }
        public string PurchasedCountryOfMfg { get; set; }
        public string Customers { get; set; }
        public string Saleable { get; set; }
        public string HarmonizedCode { get; set; }
        public string ExportLicenseNo { get; set; }
    }
}
